[package]
authors = ["Andreas Heider <andreas@heider.io>"]
categories = ["embedded", "no-std"]
description = "Firmware for Anne Pro Keyboard"
keywords = ["no-std", "arm", "cortex-m", "anne", "pro", "keyboard"]
license = "Apache-2.0"
name = "anne-key"
repository = ""
version = "0.0.2"

[dependencies]
bare-metal = "0.1.1"
cortex-m = "0.4.3"
cortex-m-semihosting = "0.2.0"
cortex-m-rtfm = "0.3.1"
vcell = "0.1.0"

[features]
default = ["use_semihosting"]
use_semihosting = []

[dependencies.cortex-m-rt]
features = ["abort-on-panic"]
version = "0.3.12"

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.1.0"

[dependencies.stm32l151]
features = ["rt"]
version = "0.2.1"

[dependencies.stm32l151-hal]
version = "0.1.0"

[profile.release]
debug = true
lto = true

[profile.dev]
debug = true
lto = true
